on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download and build Boost library
        run: |
          ./scripts/install_boost_1_71.sh
      - name: Build Solidity
        run: |
          ./scripts/build.sh
      - name: Run tests
        run: |
          ./scripts/tests.sh
