on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKER_REPOSITORY: solbuildpackpusher/solidity-buildpack-deps
      IMAGE_NAME: buildpack-deps

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image_variant: [ubuntu2004]

    steps:
      - uses: actions/checkout@v2

      - name: Upgrade ${{ env.IMAGE_NAME }}-${{ matrix.image_variant }}
        run: |
          echo ${DOCKERHUB_TOKEN} | docker login -u solbuildpackpusher --password-stdin
          scripts/ci/docker_upgrade.sh ${{ env.IMAGE_NAME }} ${{ matrix.image_variant }} ${{ env.DOCKER_REPOSITORY }}
          docker logout
