on:
  push:
    branches: [ windows-build ]
  pull_request:
    branches: [ windows-build ]

jobs:
  windows-build:

    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSVC Environment
        shell: pwsh
        run: |
                    
      - name: Install Boost
        shell: pwsh
        run: |
          cmd.exe /c '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64 && powershell'
          .\scripts\install_deps.ps1

          #- name: Install z3
          #shell: pwsh
          #run: |
          #.\scripts\install_z3.ps1
      
      - name: Install evmone
        shell: pwsh
        run: |
          .\scripts\install_evmone.ps1
          

      - name: Configure Solidity
        run: |
          cd ${{ github.workspace }}\build
          cmake -G "Visual Studio 17 2022" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DUSE_Z3=OFF -DUSE_CVC4=OFF -DBoost_DIR=${{ github.workspace }}\build\deps\boost\lib\cmake\Boost-${{ env.BOOST_VER }} ..
          #cmake -G "Visual Studio 17 2022" -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DZ3_DIR="${{ github.workspace }}\build\deps\z3\lib\cmake\z3" -DBoost_DIR="${{ github.workspace }}\build\deps\boost\lib\cmake\Boost-1.78.0" ..

      - name: Build Solidity
        run: |
          cd ${{ github.workspace }}\build
          cmake --build . --config Release -j 12

      - name: Upload Artifact 
        uses: actions/upload-artifact@v3
        with:
          name: release-windows
          path: ${{ github.workspace }}\build
